steps:
  - task: CopyFiles@2
    displayName: "Copy logs folder to staging directory"
    inputs:
      Contents: "$(Build.SourcesDirectory)/logs/**"
      TargetFolder: "$(build.artifactstagingdirectory)"
    condition: succeededOrFailed()
