steps:
  - task: CopyFiles@2
    displayName: "Copy logs folder to staging directory"
    inputs:
      Contents: "logs/**"
      TargetFolder: "$(build.artifactstagingdirectory)"
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: "Publish artifacts: logs"
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)"
      ArtifactName: logs-$(Agent.OS)
    condition: succeededOrFailed()
